### PR TITLE
Course reserves

### PR DESCRIPTION
**Pull request by shortgoblin**
Revised course reserves pages, fully removed sub-pages and revised the URLs. Amended other mentions of reserves on the policy page.

### CODE REVIEW

**Comment by evanwill** [comment]
@shortgoblin this is looking really good! I just incorporated some feedback from others. One last feedback suggestion I was wondering if you could work on:

From the [How To page](https://www.lib.uidaho.edu/services/reserve/howto.html) that is going away, could some of the points about in-library reserves and electronic reserves (appropriate and inappropriate materials, successive use, processing time, etc.) be rewritten as FAQ topics?

I think you have some of that in the FAQs already, but maybe a bit more to ensure some of those details are not lost.

**Comment by shortgoblin** [comment]
@evanwill Have added successive use and allowed materials which I think were the only things that were missing, so the FAQ is good to go. I've also removed the FAQ question about Leganto since a page on that was re-added (which I would argue for removing, but, alas, above my pay grade), as having information in more than one place tends to be confusing for the instructors and students.

**Comment by evanwill** [comment]
@shortgoblin the leganto instructions page isn't in the Navigation anywhere, so not gumming up the information--folks just wanted it so they could link to it in email etc if you weren't around to explain. So I also added the leganto FAQ item... because its the only link to that page! And it seemed like with all mention of leganto disappearing, it is worth having a bit of explanation in case people remember the name.

**Comment by evanwill** [comment]
ready to merge?

**Comment by shortgoblin** [comment]
> ready to merge?

Sorry about the wait, I'm good whenever!

**Comment by evanwill** [comment]
Thank you @shortgoblin!  :tada:  
this PR is merged and the branch is deleted (because all the commits are added to the main), will be deployed on the web soon

**Pull request merged**
